### ISSUE TITLE
How to use with collection `fetch`?

### ISSUE THREAD

**Issue by jstayton** [magalhas/backbone-react-component#18]
Hey Jose,

The examples in the README are very helpful, but all of the collection ones use a static array of model data. How does it work when the collection is loaded by calling `fetch`? I'm having trouble.

Here's what I have:

``` javascript
var User = Backbone.Model.extend({});

var Users = Backbone.Collection.extend({
  model: User,
  url: '/users.json'
});

var Child = React.createClass({
  mixins: [Backbone.React.Component.mixin],
  componentWillMount: function () {
    this.getCollection().fetch();
  },
  createRow: function (user) {
    return (
      <tr>
        <td>{user.name}</td>
        <td>{user.email}</td>
      </tr>
    );
  },
  render: function () {
    return (
      <table>
        <tr>
          <th>Name</th>
          <th>Email</th>
        </tr>
        {this.props.collection.map(this.createRow)}
      </table>
    );
  }
});

var Parent = React.createClass({
  componentWillMount: function () {
    this.users = new Users();
  },
  render: function () {
    return (
      <div>
        <Header />
        <Child collection={this.users} />
        <Footer />
      </div>
    );
  }
});

React.renderComponent(
  <Parent />,
  document.getElementById('container')
);
```

The table is rendered, the fetch is successful, but then `render` is never called after the collection `sync` event, so the table isn't updated. Which leads me to believe I'm calling `fetch` at the wrong point?

Thanks for any help you can provide!

**Comment by vamsi** [comment]
I have the problem where fetch doesn't act upon `getCollection`
with an error `Uncaught TypeError: Cannot read property 'fetch' of undefined`
