### ISSUE TITLE
Filtered collection

### ISSUE THREAD

**Issue by jbhatab** [magalhas/backbone-react-component#29]
I'm not 100% sure if this is the place for this, but I'm just gonna post it to see what you all think.

I'm trying to filter a collection by a search term and then pass that down to a list. It gets filtered properly  but when I call @getCollection() it gives me the original collection still.

```javascript
RailsBox = React.createClass
  mixins: [Backbone.React.Component.mixin]

  getInitialState: ->
    { search_term: '' }

  setSearchFilter: (search_term) ->
    @setState(search_term: search_term)

  filteredRails: ->
    search_term = @state.search_term

    bb_rails = new Evue.Collections.Rails(@props.rails)

    # This successfully filters the collection
    filteredResults = bb_rails.bySearchTerm(@state.search_term)

  render: ->
    div {},
      Filters(setSearchFilter: @setSearchFilter)
      RailsList(collection: @filteredRails())


RailsList = React.createClass
  mixins: [Backbone.React.Component.mixin]

  render: ->
    # This is where the problem happens.
    # @getCollection() returns the original results
    # but @props.collection returns the filtered results
    # I want the filtered results in collection form.
    div className: 'list-group filter-list',
      @getCollection().map (rail) =>
        RailItem(model: rail, key: rail.get('id'))

````

I'm aware I can just pass the props down to the rail list, but I want to pass the collection the rails list and call getCollection() to get the filtered results. Any ideas on how to get this to work?

**Comment by mohamedattahri** [comment]
@magalhas I'm not sure it's entirely fixed. I'm facing the same problem as @jbhatab. I'm pretty sure getCollection() always returns the first collection passed with the component and doesn't account for collection swapping.

    render(<MyComponent collection={ collectionA }, document.getElementById('body'));
    render(<MyComponent collection={ collectionB }, document.getElementById('body'));

getCollection() will always return collectionA.

**Comment by magalhas** [comment]
This is due to change in incoming versions of the lib, anyway feel free to create a PR.

Please check issue #55 about incoming changes.

**Comment by magalhas** [comment]
Btw how come on the example you provided getCollection always returns `collectionA`? The second line is indeed a different instance of a component.

**Comment by mohamedattahri** [comment]
Not sure how react-js manages the instantiation of new instances of a component. What I know so far is that I use the same component to display different collections with different filters.

**Comment by mohamedattahri** [comment]
So I’ve just took the time to check everything and it appears events are not being fired as you predicted.




Any idea where I should start to fix this?

**Comment by magalhas** [comment]
Given incoming changes this will be fixed. For the time being when you check a collection/model reference changes you could dispose of this.wrapper and instance a new one.

Cumprimentos,
José Magalhães

**Comment by mohamedattahri** [comment]
Thanks - Great work by the way.

**Comment by magalhas** [comment]
I'll try to release a beta version of the incoming release this weekend. I also intend on patching v0.7 branch with the fix for this though I'm not sure if it's worth it.

**Comment by magalhas** [comment]
@mohamedattahri feel free to try out the master :) Remember this already include all the changes for v0.8.0

**Comment by magalhas** [comment]
Also @jbhatab this was in fact occurring all this time.

**Comment by jbhatab** [comment]
Ok great, thanks. Appreciate all the fixes and keeping up with react updates.

**Comment by magalhas** [comment]
v0.8.0-beta.1 is released and it fixes this
