### ISSUE TITLE
When multiple collections are bound to a node, Backbone.Collection.fetch does not trigger re-render.

### ISSUE THREAD

**Issue by rzhou186** [magalhas/backbone-react-component#50]
Re-rendering seems to work fine when one collection is bound to a node. For example, if I create a new model in the collection, edit an existing model in the collection, or re-fetch the whole collection from the server, the node will re-render.

However, this doesn't seem to work when there are multiple collections bound to a node.

**Comment by magalhas** [comment]
That's very strange. I'll write a unit test for it to validate this bug and fix it.

**Comment by rzhou186** [comment]
Thanks. I'm using version 0.7.2, for what it's worth!

**Comment by rzhou186** [comment]
On a side note, shouldn't props be immutable? According to the README, when multiple collections are present, they need to be accessed via props (e.g. this.props.firstCollection).

Therefore, if I call `this.props.firstCollection.fetch({ ... });`, I would be mutating props.

**Comment by magalhas** [comment]
Via `@props` you'll find the JSON representation of the collection(s). Via `@getCollection()` you'll get the real collection instances. If README is making you think otherwise then it must be clarified there.

**Comment by rzhou186** [comment]
Ah, it was a bad error on my part - I overlooked something in the README.

magalhas, I sent you a private message by email. Thanks for being so responsive and sorry for mis-filing this issue.

**Comment by magalhas** [comment]
There's no problem :+1: I'll review your PR asap. Thank you very much.
