### ISSUE TITLE
Is this compatible with react-router?

### ISSUE THREAD

**Issue by ieugen** [magalhas/backbone-react-component#57]
I'm trying to integrate backbone-react-component with react-router [1], but there doesn't seem to be a direct way to do it. Any ideas if this is possible? 

Thanks,

[1] https://github.com/rackt/react-router/

**Comment by ieugen** [comment]
From my limited knowledge of both technologies, one approach might be to bind the models and collection in a function on the React class (a method similar to componentWillMount or something). 

Wdyt?

**Comment by magalhas** [comment]
I've never used `react-router` (I usually use `Backbone` for routing and models), though after checking the the docs a little bit I don't see why it wouldn't work at all. Did you find any specific issues or you're just thinking on how you should tackle it yet?

**Comment by ieugen** [comment]
I'm thinking on how to build modular web applications. One module corresponds to one feature that is mostly self contained and is integrated in the main app via routes and maybe a thin data layer. The app maintains a central data store to reuse data across features and avoid fetching when switching to a new part of the application. 

I'm using backbone-react for binding the data to react components.  My problem was how to pass the collections and models to react since react-router is declarative.  

My solution so far is to pass model and collection to RouteHandler and this makes them available to all react components that are rendered. Is nice, but there is a use case where this doesn't work: routes with parameters that render a model from a collection.

Some sample code for a Questionnaire feature:

Notice I can't supply models and collections since react-router handles instantiation for me. I just declare the handler == react component . 
````
import React from 'react';
import {Route} from 'react-router';

export default (
    <Route name='questionnaire' path="/questionnaire" handler={require('./main')}>
        <Route name="list" path="list" handler={require('./views/list')}/>
        <Route name='single' path=":questionnaireId" handler={require('./views/single')}/>
    </Route>
);
````
Passing all the collections and models downstream: 
````
// main.js -- questionnaires main view accessible at questionnaires/
import React from 'react';
import {RouteHandler} from 'react-router';
import BackboneReactMixin from 'backbone-react-component'
import questionnaires from './module'

export default React.createClass({
    mixins: [BackboneReactMixin],
    render() {
        return (
            <div>
                <p>Questionnaire</p>
                <!-- this is where we pass the collections and models to all sub views -->
                <RouteHandler collection={ {questionnaires} } model={ {questionnaire: questionnaires.first()} }/>
            </div>
        );
    }
});
````

Component to render a single questionnaire by responding to a route change like **questionnaires/1** :

Notice I need to bind the model given by the route parameter. How can I achieve this? 
```
// sindle.js
import React from 'react';
import {State} from 'react-router'
import BackboneReactMixin from 'backbone-react-component'

export default React.createClass({
    mixins: [State, BackboneReactMixin],
    render() {
        debugger;
        return (
            <div>
                <p>Questionnaire: {this.getParams().questionnaireId } </p>
            </div>
        );
    }
});
```
