### ISSUE TITLE
Is backbone-react compatible with react-bootstrap or third-party components?

### ISSUE THREAD

**Issue by ieugen** [magalhas/backbone-react-component#59]
The question boils down to: can I mixin backbone-react with third party components like react-bootstrap?

[1] http://react-bootstrap.github.io/

**Comment by magalhas** [comment]
The obvious answer is yes though it's not this mixin responsibility to guarantee compatibility with al other mixins out there. Bottom conclusion is that the mixin pattern is so good that I don't feel that there will be much incompatibility between mixins out there

**Comment by magalhas** [comment]
Anyway feel free to test it out on a simple scenario and let me know if you find any problems at all.

**Comment by ieugen** [comment]
It works. It was a silly question on my part.
