### ISSUE TITLE
Update npm and bower

### ISSUE THREAD

**Issue by MuhammadMuneer** [magalhas/backbone-react-component#61]
Integration with react router didn't work, just to realise that it was due to outdated version when installed via npm. 

With the current version cloned from git, it works well with react-router. :+1:

**Comment by magalhas** [comment]
I'm waiting for the official React's v0.13 release to release a new version of the mixin (though I plan on releasing a new beta version meanwhile). Anyway, can you share how are you passing your models and collections into the components using react-router? I'm asking this due to #60

**Comment by MuhammadMuneer** [comment]
I passed it using 'overrideCollection' and 'overrideModel' methods as suggested in the react-router example given.

**Comment by magalhas** [comment]
Nice. What do you think about those methods being named as `getDefaultCollection` and `getDefaultModel` ?

**Comment by MuhammadMuneer** [comment]
Current method names sounds good to me. I rather not name it as 'getDefault...', for the same reasons suggested in the other issue #60 (confusion with getDefaultProps).

**Comment by magalhas** [comment]
Alright. Thank you a lot for your opinion :+1:

**Comment by ieugen** [comment]
If backbone-react-component works with react 0.12, please make sure to specify that in peerDependencies. It would be a shame not to be able to use they work well together. For example, because of other dependencies not using react 0.13 yet (react-router) I can't upgrade. This leaves out backbone-react-component also. 

Regards,

**Comment by magalhas** [comment]
@ieugen 0.8.0 won't work with React 0.12. For that there's the version 0.7. In this version we're using features that are not supported on React 0.12, so keeping it compatible would introduce some ugly code to make it work.

**Comment by magalhas** [comment]
Version 0.7 is already in a separate branch and I'm ok with pushing some fixes to there if it makes sense.

**Comment by magalhas** [comment]
New version was just released (requires React v0.13)

**Comment by ieugen** [comment]
I would apreciate if you could backboprt the features to 0.7. They should work with 0.7. Thanks also for pointing out the incompatibility with react 0.12.

**Comment by magalhas** [comment]
Yes, things like `overrideModel` and `overrideCollection` can be ported into 0.7. Feel free to PR it, else I'll do it when I find some time ;)
