### ISSUE TITLE
unit tests to validate overrideModel and overrideCollection hooks

### ISSUE THREAD

**Issue by magalhas** [magalhas/backbone-react-component#64]

**Comment by magalhas** [comment]
@ieugen and @MuhammadMuneer I was coding the unit tests and I noticed the following warning on both methods:

`Warning: Don't set .props.model of the React component. Instead, specify the correct value when initially creating the element.`

Basically props should be immutable. @ieugen I'll need to change your implementation, but I think the method can work the same way.

**Comment by ieugen** [comment]
Agreed. Yes, they are going for immutability, which is nice. Go for it :)

**Comment by magalhas** [comment]
@ieugen it was a very minor change to your PR :+1:
