### ISSUE TITLE
Update backbone to 1.2.x and consider new "update" collection event

### ISSUE THREAD

**Issue by darrrk** [magalhas/backbone-react-component#82]

**Comment by magalhas** [comment]
I can do this but meanwhile feel free to open a PR for it, it looks like pretty straightforward changes :+1: Thank you for opening the issue

**Comment by darrrk** [comment]
Close this, because this kill backbone <1.2.0 compatibility

**Comment by magalhas** [comment]
@darrrk can you please elaborate why does the compatibility breaks?

**Comment by darrrk** [comment]
Since backbone 1.2.0 you can use `update` event instead [`add` and `remove`](https://github.com/magalhas/backbone-react-component/blob/master/lib/component.js#L319)
Pros:
We can use only one `update` event instead any amount of multiple `add` or/and `remove` events.
Negative:
Breaks compatibility with backbone less than 1.2.0

**Comment by magalhas** [comment]
I don't see why this change couldn't be included in the incoming version of this lib. React also includes some breaking changes in some versions and we'll keep up with it, I guess the same approach applies do Backbone. If the dev needs, simply lock backbone-react-component to the minor version (0.8 in this case).


Do you agree?


Cumprimentos,
José Magalhães

**Comment by darrrk** [comment]
Ok, giving PR

**Comment by magalhas** [comment]
Sweet :+1:

**Comment by darrrk** [comment]
#85 merged
