### ISSUE TITLE
React 0.14.0

### ISSUE THREAD

**Issue by ram-you** [magalhas/backbone-react-component#90]
Please update to the last React 0.14.0.
Thank you.

**Comment by darrrk** [comment]
:+1:

**Comment by magalhas** [comment]
Currently I've been busy with [relax](https://github.com/relax/relax), though I'm still maintaining this. Anyway, unless a PR is sent, it'll take me some weeks until I find time for this.

**Comment by magalhas** [comment]
The PR is merged. I'm going to prepare a release with it.
