### ISSUE TITLE
How to get the actual Model?

### ISSUE THREAD

**Issue by tutuca** [magalhas/backbone-react-component#93]
I notice that a component that admits a model instance stores only its json representation in `this.state.model`.

I have lots of computed values in my models. Is there a provided way to get the actual model?

**Comment by magalhas** [comment]
`this.getModel()`

**Comment by tutuca** [comment]
Consider me facepalmed. 
Sorry for opening an Issue. Thought it was the quickest way to get in contact.

**Comment by magalhas** [comment]
That's ok. No worries :)
