### ISSUE TITLE
Keeping references between model and state

### ISSUE THREAD

**Issue by mir3z** [magalhas/backbone-react-component#95]
This bug is the direct consequence of #83 

In the latest version you added `getAttributes` method which eventually returns `modelOrCollection.attributes` which is an object. As a consequence I can't compare state in  `shouldComponentUpdate` because `this.state.model` and `nextState.model` are exactly the same since they share reference. Previously it works because you were using `toJSON` which was creating a new object.

**Comment by magalhas** [comment]
Hi,

I'm sorry it took me so long to notice this. I've been off Backbone so I didn't pay enough attention to this project.

Maybe we can fix this by cloning the attributes in [here](https://github.com/magalhas/backbone-react-component/blob/master/lib/component.js#L293) and [here](https://github.com/magalhas/backbone-react-component/blob/master/lib/component.js#L297). I'm afraid of the performance drag, but we were using toJSON before which was even worse.

**Comment by mir3z** [comment]
Hello,

cloning attributes is what `toJSON` actually does, except cases where `toJSON` is overridden in a model.

Anyway cloning should fix this bug.

**Comment by magalhas** [comment]
People overriding `toJSON` was the cause of the original bug, so cloning won't bring that back.

Are you willing to create a PR?

**Comment by mir3z** [comment]
> Are you willing to create a PR?

Sure, just created
